### ISSUE TITLE
Outdated values in cache after write

### ISSUE THREAD

**Issue by FlorianFreudiger** [aleksamagicka/asus_rog_ryujin-hwmon#4]
Not a big issue but if a program requests a status (e.g. coolant temperature) and adjusts duties because of that, the values for pump/fan speeds won't be updated for another 2 seconds.

If the delay is necessary this behaviour is fine.

**Comment by aleksamagicka** [comment]
That's how hwmon drivers work, it's considered OK to lag for a bit. What's important for the program that's setting duties (ie fancontrol) is that it can read back the new duty immediately.

Although, the 2 second interval is mostly arbitrary, I can set it to 1 second if the device can handle it?

**Comment by FlorianFreudiger** [comment]
> That's how hwmon drivers work, it's considered OK to lag for a bit. What's important for the program that's setting duties (ie fancontrol) is that it can read back the new duty immediately.
> 
> Although, the 2 second interval is mostly arbitrary, I can set it to 1 second if the device can handle it?

No I think if that's common behaviour it's fine, the pump and fans might take a second to spin up anyway.

**Comment by FlorianFreudiger** [comment]
Although, maybe it should be lowered slightly to something like 1.95 or 1.9 seconds (or 3.95, 3.9 if it was to be increased to 4s) since something like `watch sensors` refreshes every 2 seconds by default and would otherwise only update the values every second cycle on average

**Comment by aleksamagicka** [comment]
Would 1.5s suffice? 1.95 and 1.9 are too weird to explain later on.

**Comment by FlorianFreudiger** [comment]
> Would 1.5s suffice? 1.95 and 1.9 are too weird to explain later on.

1.5s is also fine, haven't experienced any negative effect from spamming liquidctl status commands (running every ~0.5 seconds)

**Comment by aleksamagicka** [comment]
Thanks, just pushed the commit for 1.5s.
